inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rspec.yml

AllCops:
  UseCache: true
  TargetRubyVersion: 2.6.0
  Include:
    - bin/console
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - smart_core.gemspec

# NOTE: support for oldes ruby versions
Style/RedundantBegin:
  Enabled: false
