language: ruby
sudo: false
cache: bundler
before_install: gem install bundler
script: bundle exec rspec
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.8
  - rvm: 2.4.9
  - rvm: 2.5.7
  - rvm: 2.6.5
  - rvm: ruby-head
  - rvm: jruby-head
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
